name: compile_site

on:
  push:
    paths:
      - 'entries/*.md'
    branches:
      - main

env:
  remote: 'agnescameron/testing-template' # change this to your repo
  # need to read in as string; GA doesn't support array assignment
  INPUT_FOLDERS: "entries;"
  branch: main
jobs:
  submit:
    runs-on: ubuntu-latest
    name: Take added markdown files and compose into site
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"


      - name: Copy files to site and add layout
        run: |
            IFS=';' read -ra input_array <<< "${{ env.INPUT_FOLDERS }}"
            if [ ! -d "app/index/" ]; then
                echo "could not find entries dir"
                mkdir app/index/
            fi
            for dir in "${input_array[@]}"; do
              if [ ! -d "app/index/_${dir}" ]; then
                  echo "could not find entries dir"
                  mkdir app/index/_${dir}/
              fi
              cp -r ${dir}/* app/index/_${dir}/
              for file in app/index/_${dir}/*.md; do
                sed -i '2s/^/layout\: default\n/;' $file
              done
            done


      - name: Commit files
        run: |
            git pull
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add app/**
            git commit -m "compiled site after edit to markdown files"
            git push

