name: pull_data

on:
  schedule:
  - cron: "0 0 29 2 1" # this won't run till 2044, change it when you're ready

  # uncomment this one for debugging (will run each time you push a change)
  # push:
  #   branches:
  #     - main

env:
  # edit these:
  INPUT_CREDS: #airtable API key
  BASE_ID: #id of airtable base
  TABLE_ID: #id of airtable table
  TABLE_NAME: #whatever you want your CSV file to be called
  remote: # change this to your repo

  # these guys can stay as default unless you want to change:
  ARCHIVE_DIR: "index_archive" #this is the default home for csv files
  FILES_DIR: "entries" #this is the default home for markdown files
  branch: main
jobs:
  pull_sheet:
    runs-on: ubuntu-latest
    name: Pulling regular updates from Airtable
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: set up Python environment
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Pull Airtable data and generate markdown
        id: 'sheet_to_csv'
        env:
          INPUT_CREDS: ${{ secrets.AIRTABLE_API_KEY }}
        run: python3 scripts/pull_data.py

      - name: Check if files changed
        id: check_diff
        run: |
          echo "list changed files:"
          git diff --name-only
          
          echo "check paths of new and changed files:"
          git diff --name-only > files.txt
          git status --porcelain | grep -e '^??' | sed -e 's/^?? //g' >> files.txt
          while IFS= read -r file
          do
            echo "$file"
            if [[ $file == *.csv ]] || [[ $file == *.md ]]; then
              echo "updated files"
              echo "::set-output name=commit_files::true"
            fi
          done < files.txt

      - name: Commit files
        if: steps.check_diff.outputs.commit_files == 'true'
        run: |
            git pull
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add "$ARCHIVE_DIR" "$FILES_DIR" app/assets/thumbnails
            git commit -m "generated files based on airtable"
            git push
